export const LEVEL_MODE_CONFIG = {
  TOTAL_DISTANCE: 500,
  START_Z: 40,
  Z_INCREMENT: 5,
  PATH_1_PHASE: 0,
  PATH_2_PHASE: Math.PI,
  TORTUOSITY: 1.2,
  AMPLITUDE_X: 5.0,
  AMPLITUDE_Y: 2.1,
  OBSTACLE_DENSITY: 0.4,
  SAFE_RADIUS: 3.5,
  PORTAL_CHANCE: 0.1,
  PORTAL_MIN_SPACING: 30,
};

export const INFINITE_MODE_CONFIG = {
  TOTAL_DISTANCE: 50000, 
  START_Z: 40,
  Z_INCREMENT: 6,
  PATH_1_PHASE: 0,
  PATH_2_PHASE: Math.PI / 2,
  TORTUOSITY: 1.8,
  AMPLITUDE_X: 4.0,
  AMPLITUDE_Y: 2.0,
  OBSTACLE_DENSITY: 0.6,
  SAFE_RADIUS: 2.2,
  PORTAL_CHANCE: 0.12,
  PORTAL_MIN_SPACING: 30,
};